core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


class TestPageView(TemplateView):
    template_name = "base.html"


urlpatterns = [
    path('test', TestPageView.as_view(), name='test'),
    path('admin/', admin.site.urls),
    path('patients/', include('patients.urls', namespace='patients')),
    path('procedures/', include('procedures.urls', namespace='procedures')),
]

patients/urls.py
from django.urls import path
from patients.views import PatientListView, PatientCreateView, PatientUpdateView, PatientDeleteView

app_name = 'patients'

urlpatterns = [
    path('list/', PatientListView.as_view(), name='patient_list'),
    path('add/', PatientCreateView.as_view(), name='patient_add'),  # noqa
    path('edit/<int:pk>/', PatientUpdateView.as_view(), name='patient_edit'),  # noqa
    path('delete/<int:pk>/', PatientDeleteView.as_view(), name='patient_delete'),  # noqa

]

procedures/urls.py
from django.urls import path
from procedures.views import ProcedureCreateView, ProcedureDeleteView

app_name = 'procedures'

urlpatterns = [
     path('add/', ProcedureCreateView.as_view(), name='procedure_add'),  # noqa
    # path('edit/<int:pk>/', PatientUpdateView.as_view(), name='patient_edit'),  # noqa
    path('delete/<int:pk>/', ProcedureDeleteView.as_view(), name='procedure_delete'),  # noqa

]

templates/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

  <link rel="stylesheet" href="{% static 'css/common.css' %}">

templates/partials/messages.html
{% if messages %}
<div class="position-fixed top-0 end-0 p-3" style="z-index: 1055;">
    {% for message in messages %}
        <div class="toast align-items-center 
            {% if 'error' in message.tags %}bg-danger text-white{% elif 'warning' in message.tags %}bg-warning text-dark{% elif 'success' in message.tags %}bg-success text-white{% else %}bg-info text-dark{% endif %} 
            border-0 mb-2" 
            role="alert" aria-live="assertive" aria-atomic="true"
        >
            <div class="d-flex">
                <div class="toast-body">
                    {{ message }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const toastElList = [].slice.call(document.querySelectorAll('.toast'))
        toastElList.forEach(function (toastEl) {
            const bsToast = new bootstrap.Toast(toastEl, { delay: 3000, autohide: true })
            bsToast.show()
        })
    })
</script>
{% endif %}

templates/partials/navbar.html
<div class="container d-flex align-items-center">
    <!-- Logo genérica -->
    <i class="bi bi-bandaid-fill me-2" style="font-size: 1.5rem; color:white;"></i>
    
    <a class="navbar-brand mb-0 h1" href="/">Clínica de Podologia</a>
    
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto ms-3">
            <!-- Dropdown Pacientes -->
            <li class="nav-item dropdown me-2">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Pacientes
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'patients:patient_add' %}"><i class="bi bi-person-fill-add"></i> Novo Paciente</a></li>
                    <li><a class="dropdown-item" href="{% url 'patients:patient_list' %}"><i class="bi bi-search"></i> Lista de Pacientes</a></li>
                </ul>
            </li>

            <!-- Dropdown Procedimentos -->
            <li class="nav-item dropdown">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Procedimentos
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url "procedures:procedure_add" %}"><i class="bi bi-person-lines-fill"></i> Registrar Procedimento</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

templates/partials/pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination pagination-sm justify-content-center">
      <!-- Link para a primeira página -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{{ query_params }}&page=1">
            <i class="bi bi-chevron-double-left"></i>
          </a>
        </li>
      {% endif %}

      <!-- Link para a página anterior -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{{ query_params }}&page={{ page_obj.previous_page_number }}">
            <i class="bi bi-caret-left"></i>
          </a>
        </li>
      {% endif %}

      <!-- Links para as páginas intermediárias -->
      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?{{ query_params }}&page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?{{ query_params }}&page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      <!-- Link para a próxima página -->
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{{ query_params }}&page={{ page_obj.next_page_number }}">
            <i class="bi bi-caret-right"></i>
          </a>
        </li>
      {% endif %}

      <!-- Link para a última página -->
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{{ query_params }}&page={{ page_obj.paginator.num_pages }}">
            <i class="bi bi-chevron-double-right"></i>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}