core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


class TestPageView(TemplateView):
    template_name = "base.html"


urlpatterns = [
    path('test', TestPageView.as_view(), name='test'),
    path('admin/', admin.site.urls),
    path('patients/', include('patients.urls', namespace='patients')),
    path('procedures/', include('procedures.urls', namespace='procedures')),
]

patients/urls.py
from django.urls import path
from patients.views import PatientListView, PatientCreateView, PatientUpdateView, PatientDeleteView

app_name = 'patients'

urlpatterns = [
    path('list/', PatientListView.as_view(), name='patient_list'),
    path('add/', PatientCreateView.as_view(), name='patient_add'),  # noqa
    path('edit/<int:pk>/', PatientUpdateView.as_view(), name='patient_edit'),  # noqa
    path('delete/<int:pk>/', PatientDeleteView.as_view(), name='patient_delete'),  # noqa

]

procedures/urls.py
from django.urls import path
from procedures.views import ProcedureCreateView, ProcedureDeleteView

app_name = 'procedures'

urlpatterns = [
     path('add/', ProcedureCreateView.as_view(), name='procedure_add'),  # noqa
    # path('edit/<int:pk>/', PatientUpdateView.as_view(), name='patient_edit'),  # noqa
    path('delete/<int:pk>/', ProcedureDeleteView.as_view(), name='procedure_delete'),  # noqa

]

patients/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from datetime import date


class Patient(models.Model):
    """ Modelo para armazenar informações do paciente """

    first_name = models.CharField(
        max_length=30,
        help_text="Primeiro nome do paciente",
        null=False,
        blank=False
    )

    last_name = models.CharField(
        max_length=30,
        help_text="Sobrenome do paciente",
        null=False,
        blank=False
    )

    date_of_birth = models.DateField(
        help_text="Data de nascimento do paciente"
    )

    medical_record_number = models.CharField(
        max_length=20,
        unique=True,
        help_text="Número do prontuário médico"
    )

    is_active = models.BooleanField(
        default=True,
        help_text="Indica se o paciente está ativo"
    )

    last_schedule_date = models.DateField(
        null=True,
        blank=True,
        help_text="Data do último agendamento do paciente"
    )

    gender = models.CharField(
        max_length=10,
        choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')],
        help_text="Gênero do paciente"
    )

    phone_1 = PhoneNumberField(null=True, blank=True)
    phone_2 = PhoneNumberField(null=True, blank=True)

    email = models.EmailField(
        null=True,
        blank=True,
        help_text="Endereço de e-mail do paciente"
    )

    @property
    def age(self):
        """Retorna a idade do paciente em anos."""
        if not self.date_of_birth:
            return None
        today = date.today()
        return (
            today.year - self.date_of_birth.year -
            ((today.month, today.day) <
             (self.date_of_birth.month, self.date_of_birth.day))
        )

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.medical_record_number})"

patients/forms.py
from cProfile import label
from django import forms
from patients.models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = [
            'first_name', 'last_name', 'date_of_birth', 'gender',
            'phone_1', 'phone_2', 'email'
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: João'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: Silva'}),
            'date_of_birth': forms.DateInput(
                attrs={'type': 'date', 'class': 'form-control'},
                format='%Y-%m-%d'  # <- formato que o input date espera
            ),
            'gender': forms.Select(attrs={'class': 'form-select'}),
            'phone_1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(99) 99999-9999'}),
            'phone_2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '(99) 99999-9999'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email@exemplo.com'}),
        }

        labels = {
            'first_name': 'Primeiro Nome',
            'last_name': 'Sobrenome',
            'date_of_birth': 'Data de Nascimento',
            'gender': 'Gênero',
            'phone_1': 'Telefone 1',
            'phone_2': 'Telefone 2',
            'email': 'E-mail',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.date_of_birth:
            self.fields['date_of_birth'].initial = self.instance.date_of_birth
        self.fields['date_of_birth'].input_formats = ['%Y-%m-%d']

patients/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from patients.models import Patient
from django.db.models import Q
from patients.forms import PatientForm
from django.urls import reverse_lazy
from django.contrib import messages


class PatientListView(ListView):
    model = Patient
    template_name = 'patients/list.html'
    context_object_name = 'patients'
    paginate_by = 10
    ordering = ['first_name', 'last_name',]

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get('search', '')
        status = self.request.GET.get('status', '')

        if search:
            queryset = queryset.filter(
                Q(first_name__icontains=search) |
                Q(last_name__icontains=search) |
                Q(medical_record_number__icontains=search)
            )

        if status == 'ativo':
            queryset = queryset.filter(is_active=True)
        elif status == 'inativo':
            queryset = queryset.filter(is_active=False)

        return queryset


class PatientCreateView(CreateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patients/create.html'
    success_url = reverse_lazy('patients:patient_list')

    def form_valid(self, form):
        messages.success(
            self.request, f"Paciente {form.instance.first_name} criado com sucesso!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, f"Erro ao cadastrar o paciente {form.instance.first_name}.")
        return super().form_invalid(form)


class PatientUpdateView(UpdateView):
    model = Patient
    form_class = PatientForm
    template_name = 'patients/update.html'
    success_url = reverse_lazy('patients:patient_list')

    def form_valid(self, form):
        messages.success(
            self.request, f"Paciente {form.instance.first_name} atualizado com sucesso!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, f"Erro ao atualizar o paciente {form.instance.first_name}.")
        return super().form_invalid(form)


class PatientDeleteView(DeleteView):
    model = Patient
    template_name = 'patients/list.html'
    success_url = reverse_lazy('patients:patient_list')

    def post(self, request, *args, **kwargs):
        patient = self.get_object()
        messages.success(
            self.request, f"Paciente {patient.first_name} excluído com sucesso!")
        return super().delete(request, *args, **kwargs)

patients/templates/patients/modals/delete_modal.html
<!-- Modal de confirmação -->
<div class="modal fade" id="deleteModal{{ patient.pk }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ patient.pk }}" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-secondary text-white">
        <h6 class="modal-title" id="deleteModalLabel{{ patient.pk }}">
          Confirmar Exclusão
        </h6>
      </div>
      <div class="modal-body">
        Tem certeza que deseja excluir o paciente <strong>{{ patient.first_name }} {{ patient.last_name }}</strong>?
      </div>
      <div class="modal-footer">
        <form method="post" action="{% url 'patients:patient_delete' patient.pk %}">
          {% csrf_token %}
          <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-sm btn-danger">Excluir</button>
        </form>
      </div>
    </div>
  </div>
</div>

patients/templates/patients/modals/procedures_modal.html
<!-- Modal de procedimentos -->
<div class="modal fade" id="proceduresModal{{ patient.pk }}" tabindex="-1" aria-labelledby="proceduresModalLabel{{ patient.pk }}" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="proceduresModalLabel{{ patient.pk }}">Procedimentos de {{ patient.first_name }} {{ patient.last_name }}</h5>
      </div>
      <div class="modal-body">
        {% if patient.procedures.exists %}
        <table class="table table-striped table-sm text-small text-center">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Procedimento</th>
                    <th>Observações</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for procedure in patient.procedures.all %}
                <tr>
                    <td>{{ procedure.procedure_date|date:"d/m/Y" }}</td>
                    <td>{{ procedure.name }}</td>
                    <td>{{ procedure.notes }}</td>
                    <td>
                        <form method="post" action="{% url 'procedures:procedure_delete' procedure.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="bi bi-trash3-fill"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="text-center">Nenhum procedimento registrado.</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>